; Script generated by Antigravity for YTTV Installer Compilation
; See Inno Setup documentation for details on customizing this script.

#define MyAppName "YTTV"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "YTTV Media Hub"
#define MyAppExeName "YTTV.exe"

[Setup]
; Unique AppId for registry/unistaller purposes
AppId={{D37BF90E-85EC-44B7-9F93-4B9F63071A2E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Save the compiled installer in the repository root directory
OutputDir=.
OutputBaseFilename=YTTV_Setup_x64
Compression=lzma
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
PrivilegesRequired=admin

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Copy all published self-contained files recursively
Source: "src-csharp\YTTV\bin\Release\net8.0-windows\win-x64\publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
