-- ==========================================
-- Supabase Schema for localyt.tv Web Demo
-- Run this script in the Supabase SQL Editor
-- ==========================================

-- 1. Playlists Table
CREATE TABLE IF NOT EXISTS playlists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  custom_ascii TEXT,
  custom_thumbnail_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Playlist Items / Videos Table
CREATE TABLE IF NOT EXISTS playlist_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  playlist_id BIGINT REFERENCES playlists(id) ON DELETE CASCADE,
  video_url TEXT NOT NULL,
  video_id TEXT NOT NULL,
  title TEXT NOT NULL,
  thumbnail_url TEXT,
  author TEXT,
  view_count TEXT DEFAULT '0',
  position INT DEFAULT 0,
  is_local INT DEFAULT 0,
  duration_seconds INT,
  description TEXT,
  added_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Orb Presets & Customizations
CREATE TABLE IF NOT EXISTS orb_presets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  visualizer_color TEXT DEFAULT '#ffffff',
  visualizer_mode TEXT DEFAULT 'bar',
  visualizer_gradient TEXT,
  banner_left TEXT,
  banner_right TEXT,
  orb_image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. App Header Banners
CREATE TABLE IF NOT EXISTS app_banners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  image_url TEXT NOT NULL,
  banner_side TEXT DEFAULT 'left', -- 'left' or 'right'
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) & Grant Public Read Access
ALTER TABLE playlists ENABLE ROW LEVEL SECURITY;
ALTER TABLE playlist_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE orb_presets ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_banners ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read access for playlists" ON playlists FOR SELECT USING (true);
CREATE POLICY "Public read access for playlist_items" ON playlist_items FOR SELECT USING (true);
CREATE POLICY "Public read access for orb_presets" ON orb_presets FOR SELECT USING (true);
CREATE POLICY "Public read access for app_banners" ON app_banners FOR SELECT USING (true);

-- Seed Initial Demo Playlists
INSERT INTO playlists (id, name, description) VALUES
(1, 'Lo-Fi Beats & Chill', 'Curated lo-fi music for work, coding, and focus sessions.'),
(2, 'Synthwave & Retro Outrun', 'Analog synth tracks, neon visuals, and retro beats.'),
(3, 'Tech & Development Talks', 'Keynotes, tutorials, and engineering talks.')
ON CONFLICT (id) DO NOTHING;

-- Seed Initial Demo Videos
INSERT INTO playlist_items (playlist_id, video_url, video_id, title, thumbnail_url, author, view_count, position) VALUES
(1, 'https://www.youtube.com/watch?v=jfKfPfyJRdk', 'jfKfPfyJRdk', 'Lofi Hip Hop Radio - Beats to Relax/Study to', 'https://i.ytimg.com/vi/jfKfPfyJRdk/hqdefault.jpg', 'Lofi Girl', '1240000', 0),
(1, 'https://www.youtube.com/watch?v=tNkZs56sUdg', 'tNkZs56sUdg', 'Lofi Cafe - Ambient Lofi Beats to Work/Study', 'https://i.ytimg.com/vi/tNkZs56sUdg/hqdefault.jpg', 'Lofi Records', '450000', 1),
(2, 'https://www.youtube.com/watch?v=4xDzrJKXOOY', '4xDzrJKXOOY', 'Synthwave Radio - Chill Synth / Retro Beats', 'https://i.ytimg.com/vi/4xDzrJKXOOY/hqdefault.jpg', 'Lofi Girl Synthwave', '883000', 0)
ON CONFLICT (id) DO NOTHING;
